### ISSUE TITLE
Könyv kölcsönönzés

### ISSUE THREAD

**Issue by balintdom** [valkimarton/library-backend#2]
a kölcsönzés lebonyolításához szükséges lenne lekérdezni az egyes regényekhez tartozó könyvek állapotát. Ezen kívül szerintem több értelme lenne az egyes könyvekhez kapcsolni a kiadás dátumát, mint a regényekhez. Ez utóbbi csak érdekesség, az előbbi viszont releváns információt hordozhat.

**Comment by valkimarton** [comment]
- GET ap/writing/{writingId}/books    returns all books for a writing
- GET ap/writing/{writingId}/books_available    returns all available books for a writing
